### ISSUE TITLE
Data Processing

### ISSUE THREAD

**Issue by voremargot** [UBC-MDS/Cost_of_living_py#4]
This thread is for questions and comments about the data preprocessing

**Comment by hjw0703** [comment]
Data is processed and my remarks related to processing is as below. Welcome to provide comments on this. 
 - Column 'Imported Beer (0.33 liter bottle)' was dropped to avoid confusion because there are two columns with exactly the same name and different values.
 -  Only consider one person's living cost, which means 3 bedrooms rent and meal for 2 people are removed.
-  One way ticket(local transport) was discarded as monthly pass of transportation is already included.
- International Primary School, Yearly for 1 Child was dropped as our target personnel is single.
-  Rent for one person is the average of rent for a one-bedroom in city center and outside city center.
- Public transportation assumes the person takes taxi for 30 km in a month and uses monthly pass in other days.
-  Liquor and cigarettes cost are included in entertainment category.
- Fitness fee includes monthly membership in fitness club only(tennis court rent is uncommon and was dropped).
-  Shopping includes buying jeans, summer dress, sports shoes, leather shoes one for each in a month.
-  Childcare fee is the monthly cost for one preschool child.
- Monthly saving is how much USD the person is likely to save in a month, which calculated by monthly salary(after tax) subtracts all the costs mentioned above(except the childcare fee).
- Property price per square meter is the average price of buying a house in city center and outside center.
- The currency unit has been converted from Euro to USD and the current rate is 1 Euro = 1.14 USD.

**Comment by Arushi282** [comment]
Hi @hjw0703, 

Thank you for providing such a detailed overview of our preprocessed data, my only concern is that data for owning a car is not provided, we will be including a visualization where users can compare the cost of buying a car in different cities.
